export const USERS_ACTIONS = {
    SET_USERS: 'SET_USERS',
    SET_NEW_USER: 'SET_NEW_USER',
    SET_EDITING_USER: 'SET_EDITING_USER',
    SET_IS_EDITING: 'SET_IS_EDITING',
    ADD_USER: 'ADD_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    RESET_FORM: 'RESET_FORM'
  };